# Generated by Django 6.0.5 on 2026-05-31 03:59

import django.db.models.deletion
import ekspor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siswa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEkspor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('docx', 'Microsoft Word (.docx)'), ('pdf', 'PDF (.pdf)')], max_length=5, verbose_name='Format File')),
                ('rentang_mulai', models.DateField(verbose_name='Dari Tanggal')),
                ('rentang_selesai', models.DateField(verbose_name='Sampai Tanggal')),
                ('file_path', models.FileField(blank=True, upload_to=ekspor.models.ekspor_upload_path, verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Digenerate')),
                ('digenerate_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_ekspor', to=settings.AUTH_USER_MODEL, verbose_name='Digenerate Oleh')),
                ('siswa', models.ForeignKey(blank=True, help_text='Kosong jika ekspor semua siswa (laporan global admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_ekspor', to='siswa.siswa', verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Log Ekspor',
                'verbose_name_plural': 'Log Ekspor',
                'ordering': ['-created_at'],
            },
        ),
    ]
