# Generated by Django 6.0.5 on 2026-06-13 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriPerencanaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Kategori Perencanaan',
                'verbose_name_plural': 'Kategori Perencanaan',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama Client')),
                ('instansi', models.CharField(max_length=200, verbose_name='Instansi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telp', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Telp')),
                ('bidang', models.ManyToManyField(related_name='clients', to='master.jurusan', verbose_name='Bidang / Jurusan')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Perencanaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=255, verbose_name='Program')),
                ('kegiatan', models.CharField(max_length=255, verbose_name='Kegiatan')),
                ('indikator_pencapaian', models.CharField(max_length=255, verbose_name='Indikator Pencapaian')),
                ('waktu', models.DateField(verbose_name='Waktu / Tanggal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perencanaan_set', to='perencanaan.client', verbose_name='Client / Sasaran')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perencanaan_set', to='perencanaan.kategoriperencanaan', verbose_name='Kategori Perencanaan')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perencanaan_set', to='siswa.siswa', verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Perencanaan',
                'verbose_name_plural': 'Perencanaan',
                'ordering': ['-waktu', '-created_at'],
            },
        ),
    ]
