# Generated by Django 6.0.5 on 2026-06-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perencanaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perencanaan',
            name='indikator_pencapaian',
            field=models.TextField(verbose_name='Indikator Pencapaian'),
        ),
        migrations.AlterField(
            model_name='perencanaan',
            name='kegiatan',
            field=models.TextField(verbose_name='Kegiatan'),
        ),
        migrations.AlterField(
            model_name='perencanaan',
            name='program',
            field=models.TextField(verbose_name='Program'),
        ),
    ]
