# Generated by Django 6.0.5 on 2026-06-14 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perencanaan', '0002_alter_perencanaan_indikator_pencapaian_and_more'),
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriperencanaan',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategori_perencanaan_set', to='siswa.siswa', verbose_name='Siswa'),
        ),
        migrations.AlterField(
            model_name='kategoriperencanaan',
            name='nama',
            field=models.CharField(max_length=100, verbose_name='Nama Kategori'),
        ),
        migrations.AlterField(
            model_name='perencanaan',
            name='program',
            field=models.TextField(verbose_name='KategoriPerencanaanProgram'),
        ),
        migrations.AddConstraint(
            model_name='kategoriperencanaan',
            constraint=models.UniqueConstraint(fields=('siswa', 'nama'), name='unique_kategori_per_siswa'),
        ),
    ]
