# Generated by Django 6.0.5 on 2026-06-15 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perencanaan', '0003_kategoriperencanaan_siswa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_set', to='perencanaan.kategoriperencanaan', verbose_name='Kategori Perencanaan')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Program',
                'ordering': ['nama'],
            },
        ),
        migrations.AlterField(
            model_name='perencanaan',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perencanaan_set', to='perencanaan.program', verbose_name='Program'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('kategori', 'nama'), name='unique_program_per_kategori'),
        ),
    ]
