# Generated by Django 6.0.5 on 2026-06-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perencanaan', '0004_program_alter_perencanaan_program_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='program',
            name='unique_program_per_kategori',
        ),
        migrations.AddField(
            model_name='program',
            name='deskripsi',
            field=models.TextField(blank=True, verbose_name='Deskripsi'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('nama',), name='unique_program_nama'),
        ),
        migrations.RemoveField(
            model_name='program',
            name='kategori',
        ),
    ]
