# Generated by Django 6.0.5 on 2026-06-15 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perencanaan', '0005_remove_program_unique_program_per_kategori_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='siswa_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'siswa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_set', to=settings.AUTH_USER_MODEL, verbose_name='Siswa (User)'),
        ),
    ]
