# Generated by Django 6.0.5 on 2026-07-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perencanaan', '0006_program_siswa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perencanaan',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Selesai'),
        ),
    ]
