# Generated by Django 6.0.5 on 2026-05-31 03:59

import django.db.models.deletion
import laporan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Kegiatan')),
                ('uraian_pekerjaan', models.TextField(verbose_name='Uraian Pekerjaan')),
                ('hasil_progress', models.TextField(verbose_name='Hasil / Progress')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_harian', to='siswa.siswa', verbose_name='Siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laporan_harian', to='master.tahunajaran', verbose_name='Tahun Ajaran')),
            ],
            options={
                'verbose_name': 'Laporan Harian',
                'verbose_name_plural': 'Laporan Harian',
                'ordering': ['-tanggal', '-created_at'],
                'unique_together': {('siswa', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='FotoBukti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=laporan.models.foto_upload_path, verbose_name='Foto Bukti')),
                ('keterangan', models.CharField(blank=True, max_length=200, verbose_name='Keterangan Foto')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Diunggah')),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_bukti', to='laporan.laporanharian', verbose_name='Laporan Harian')),
            ],
            options={
                'verbose_name': 'Foto Bukti',
                'verbose_name_plural': 'Foto Bukti',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
