# Generated by Django 6.0.5 on 2026-07-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_laporanharian_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporanharian',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dibuat'),
        ),
    ]
