# Generated by Django 6.0.5 on 2026-06-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('siswa', 'Siswa'), ('kepala_sekolah', 'Kepala Sekolah'), ('pembimbing', 'Pembimbing')], default='siswa', max_length=15, verbose_name='Role'),
        ),
    ]
