# Generated by Django 6.0.5 on 2026-05-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Jurusan')),
                ('kode', models.CharField(help_text='Singkatan jurusan, contoh: RPL, DKV', max_length=10, unique=True, verbose_name='Kode Jurusan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Jurusan',
                'verbose_name_plural': 'Jurusan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Format: 2025/2026', max_length=20, unique=True, verbose_name='Tahun Ajaran')),
                ('is_aktif', models.BooleanField(default=False, help_text='Hanya satu tahun ajaran yang boleh aktif', verbose_name='Tahun Ajaran Aktif')),
            ],
            options={
                'verbose_name': 'Tahun Ajaran',
                'verbose_name_plural': 'Tahun Ajaran',
                'ordering': ['-nama'],
            },
        ),
    ]
