# Generated by Django 6.0.5 on 2026-05-31 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembimbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('nip', models.CharField(help_text='Nomor Induk Pegawai', max_length=30, unique=True, verbose_name='NIP')),
                ('jabatan', models.CharField(blank=True, max_length=100, verbose_name='Jabatan')),
                ('no_hp', models.CharField(blank=True, max_length=20, verbose_name='No. HP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'pembimbing'}, on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing', to=settings.AUTH_USER_MODEL, verbose_name='Akun User')),
            ],
            options={
                'verbose_name': 'Pembimbing',
                'verbose_name_plural': 'Pembimbing',
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('nis', models.CharField(help_text='Nomor Induk Siswa', max_length=20, unique=True, verbose_name='NIS')),
                ('angkatan', models.CharField(help_text='Tahun masuk, contoh: 2024', max_length=10, verbose_name='Angkatan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siswa_set', to='master.jurusan', verbose_name='Jurusan')),
                ('pembimbing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siswa_set', to='siswa.pembimbing', verbose_name='Pembimbing')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siswa_set', to='master.tahunajaran', verbose_name='Tahun Ajaran')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to=settings.AUTH_USER_MODEL, verbose_name='Akun User')),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Siswa',
                'ordering': ['nama_lengkap'],
            },
        ),
    ]
